repos:
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        additional_dependencies:
          - tomli
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.6.0'
    hooks:
      - id: mypy
        additional_dependencies:
          - 'pydantic'
          - 'types-PyYAML'
          - 'types-requests'
        exclude: '(?x)(test\_.*|conftest\.py|docs/conf\.py)'
        args: [--config, mypy.ini]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.292
    hooks:
      - id: ruff
        args: [--config, ruff.toml]
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        additional_dependencies:
          - 'pydocstyle[toml]'
        args: [--config, pydocstyle.ini]
  - repo: local
    hooks:
      - id: update-docs-requirements-txt
        name: update-docs-requirements-txt
        description: 'Generate docs/requirements.txt based on poetry.lock group docs'
        entry: poetry
        args: [export, --format, requirements.txt, --only, docs, --without-hashes, --output, docs/requirements.txt]
        language: system
        pass_filenames: false
  - repo: local
    hooks:
      - id: update-ci-requirements-txt
        name: update-ci-requirements-txt
        description: 'Generate ci/requirements.txt based on poetry.lock group ci'
        entry: poetry
        args: [export, --format, requirements.txt, --only, ci, --without-hashes, --output, ci/requirements.txt]
        language: system
        pass_filenames: false
  - repo: local
    hooks:
      - id: check-poetry-lock
        name: check-poetry-lock
        description: 'Check poetry.lock file is in sync with pyproject.toml'
        entry: poetry
        args: [check, --lock]
        language: system
        pass_filenames: false
  - repo: local
    hooks:
      - id: update_configs
        name: update_configs
        description: 'Update mypy.ini, pytest.ini, .github/workflows/plugins.yml, tox.ini'
        entry: ./update_configs.py
        language: script
        pass_filenames: false
