# contains code style and formatting configuration for the complete project
[tool.poetry]
name = "bodhilib"
version = "0.1.11"
description = "intuitive and powerful library to work with LLMs"
authors = ["Amir Nagri <amir.nagri@proton.me>"]
readme = "README.md"
packages = [
  { include = "bodhilib", from = "src" },
  { include = "bodhiext", from = "src" },
]
license = "MIT"
include = ["LICENSE"]

[tool.poetry.dependencies]
python = "^3.8.1,<3.12"
jinja2 = "^3.1.2"
pluggy = "^1.2.0"
pydantic = "^1"

[tool.poetry.group.dev.dependencies]
pre-commit = "^3.3.3"
flake8 = "^6.1.0"
mypy = "^1.4.1"
ruff = "^0.0.284"
codespell = "^2.2.5"

[tool.poetry.group.test.dependencies]
pytest = "^7.4.0"
pytest-cov = "^4.1.0"
pytest-socket = "^0.6.0"
pytest-dotenv = "^0.5.2"
pytest-timeout = "^2.1.0"
python-dotenv = "^1.0.0"

[tool.poetry.group.docs.dependencies]
sphinx = "^7.1.2"
sphinx-copybutton = "^0.5.2"
sphinx-rtd-theme = "^1.3.0"
pydocstyle = "^6.3.0"
toml = "^0.10.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.plugins.bodhilib]
"bodhiext.data_loader" = "bodhiext.data_loader"
"bodhiext.splitter" = "bodhiext.splitter"
"bodhiext.prompt_source" = "bodhiext.prompt_source"
