# contains code style and formatting configuration for the complete project
[tool.poetry]
name = "bodhilib-mono"
version = "0.1.0"
description = "intuitive and powerful library to work with LLMs"
authors = ["Amir Nagri <amir.nagri@proton.me>"]

[tool.poetry.dependencies]
python = "^3.8.1,<3.12"

[tool.poetry.group.dev.dependencies]
black = "^23.7.0"
flake8 = "^6.1.0"
isort = "^5.12.0"
mypy = "^1.4.1"
pre-commit = "^3.3.3"
ruff = "^0.0.284"
pydantic = "^1"

[tool.poetry.group.docs.dependencies]
autodoc-pydantic = "^1.9.0"
myst-parser = "^2.0.0"
sphinx = "^6.2.1"
sphinx-autobuild = "^2021.3.14"
sphinx-book-theme = "^1.0.1"
sphinx-copybutton = "^0.5.2"
esbonio = "^0.16.1"
doc8 = "^1.1.1"
pydocstyle = "^6.3.0"

[tool.black]
line-length = 120
target-version = ['py38']
preview = true
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.mypy]
python_version = 3.8
warn_return_any = true
warn_unused_configs = true
warn_unused_ignores = true
ignore_missing_imports = true
disallow_incomplete_defs = true
plugins = ['pydantic.mypy']
disallow_untyped_defs = true
# disallow_untyped_calls = true
exclude = ['test\_.*', 'conftest\.py', 'docs/conf\.py']
namespace_packages = true
explicit_package_bases = true
mypy_path = ["libs/bodhilib", "libs/bodhilib.cohere"]

[tool.ruff]
target-version = "py38"
select = ["E", "F", "B"]
ignore = []
fixable = ["ALL"]
unfixable = []
exclude = [
  ".bzr",
  ".direnv",
  ".eggs",
  ".git",
  ".git-rewrite",
  ".hg",
  ".mypy_cache",
  ".nox",
  ".pants.d",
  ".pytype",
  ".ruff_cache",
  ".svn",
  ".tox",
  ".venv",
  "__pypackages__",
  "_build",
  "buck-out",
  "build",
  "dist",
  "node_modules",
  "venv",
]
per-file-ignores = {}
line-length = 120
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"
fix = true

[tool.pydocstyle]
match = '^(?!test_|conf|conftest).*\.py$'
