# this file is automatically generated and overwritten by CI process
# to modify the content, modify the CI workflow file - .github/workflows/main.yml, job: "Update poetry and _version.py"
__version__ = "0.1.3"
