# action.yml
name: poetry-install-without-caching
description: A non-cached environment to test plugins against various bohdilib versions.

inputs:
  python-version:
    description: Python version, supporting MAJOR.MINOR only
    required: true
    default: '3.8'

  pipx-version:
    description: Pipx version
    required: false
    default: 1.2.0

  poetry-version:
    description: Poetry version
    required: false
    default: 1.6.1

  working-directory:
    description: Directory to run install-command in
    required: true

  bodhilib-version:
    description: Bodhilib version to override and install
    required: true

runs:
  using: composite
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install poetry using pipx
      shell: bash
      run: |
        pipx install poetry==${{ inputs.poetry-version }} --python python${{ inputs.python-version }}
    - name: Install bodhilib with given release version
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        version="${{ inputs.bodhilib-version }}"
        poetry add bodhilib==${version}
        poetry install --compile --sync
    - name: Install root poetry ci dependencies
      if: env.CACHE_HIT != 'true' && inputs.setup == 'true'
      shell: bash
      working-directory: '.'
      run: |
        poetry install --only ci
    - name: Install root poetry ci dependencies
      shell: bash
      run: |
        pip install -r ci/requirements.txt
