name: run-test
description: run test

inputs:
  working-directory:
    description: Directory to run commands in
    required: true
  codecov-token:
    description: Codecov token
    required: true

runs:
  using: composite
  steps:
    - name: Validate input args
      shell: bash
      run: |
        # fail if working dir does not exists
        if [[ ! -d "${{ inputs.working-directory }}" ]]; then
          echo "Working directory does not exist: ${{ inputs.working-directory }}"
          exit 1
        fi
        # fail if working dir does not have pyproject.toml
        if [[ ! -f "${{ inputs.working-directory }}/pyproject.toml" ]]; then
          echo "Working directory does not have pyproject.toml: ${{ inputs.working-directory }}"
          exit 1
        fi
    - name: set $PROJECT_ID
      shell: bash
      run: |
        if [[ "${{ inputs.working-directory }}" == "core" ]]; then
          PROJECT_ID=core
        else
          PROJECT_ID=$(echo ${{ inputs.working-directory }} | sed 's/plugins\///')
        fi
        echo "PROJECT_ID=$PROJECT_ID" # debug
        echo "PROJECT_ID=$PROJECT_ID" >> $GITHUB_ENV
    - name: Set up Python with Poetry
      uses: ./.github/actions/setup
      with:
        working-directory: ${{ inputs.working-directory }}
    - name: Copy .env.ci to .env.test
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        cp .env.ci .env.test
    - name: Run tests
      shell: bash
      run: |
        make ci.test ${PROJECT_ID}
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        env_vars: OS,PYTHON
        files: ${{ inputs.working-directory }}/coverage.xml
        flags: unittests,${PROJECT_ID}
      env:
        CODECOV_TOKEN: ${{ inputs.codecov-token }}
