name: core

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - v*
    paths:
      - core/**
      - .github/**
  workflow_dispatch:
    branches:
      - main
    inputs:
      release:
        description: 'Release type: dev (only build, no release), pre (pre-release), release (full-release)?'
        type: choice
        options:
          - dev
          - pre
          - release
        required: true
        default: dev

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: pre-commit
        uses: ./.github/actions/pre-commit
        with:
          working-directory: core
  test:
    needs: [pre-commit]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run Test
        uses: ./.github/actions/run-test
        with:
          working-directory: core
          codecov-token: ${{ secrets.CODECOV_TOKEN }}
  prerelease:
    needs: [pre-commit, test]
    if: ${{ github.event.inputs.release == 'pre' }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Pre-release
        uses: ./.github/actions/release
        with:
          working-directory: core
          release: ${{ github.event.inputs.release }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  release:
    needs: [pre-commit, test]
    if: ${{ github.event.inputs.release == 'release' }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Release
        uses: ./.github/actions/release
        with:
          working-directory: core
          release: ${{ github.event.inputs.release }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
